In [15]:
import pandas as pd

In [16]:
import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
env_path = Path(__file__).parent.parent / '.env' if '__file__' in globals() else Path('../.env')
load_dotenv(env_path)

# Get the fundamental data path from environment variable
FUNDAMENTAL_PATH = Path(os.getenv('FUNDAMENTAL_FEATURE_PATH', '../fundamental_data'))

# print(f"Fundamental data path: {FUNDAMENTAL_PATH}")
print(f"Path exists: {FUNDAMENTAL_PATH.exists()}")

Path exists: True

In [17]:
pd.set_option('display.max_columns', 100)

## pull AAPL income, balance sheet, cashflow

#### parquet (column-wise)

In [18]:
# Read the latest AAPL parquet file using the environment variable path
aapl_parquet_path = FUNDAMENTAL_PATH / "AAPL" / "AAPL_combined_factors_latest.parquet"
aapl_financials = pd.read_parquet(aapl_parquet_path)
# print(f"Loaded from: {aapl_parquet_path}")
aapl_financials.head()

,quarterly_net_income,quarterly_revenue,quarterly_gross_profit,quarterly_operating_income,quarterly_ebit,quarterly_interest_exp,quarterly_ocf,quarterly_capex,quarterly_shareholder_equity,quarterly_total_assets,quarterly_total_liabilities,quarterly_current_assets,quarterly_current_liab,quarterly_inventory,quarterly_total_debt,quarterly_cash,quarterly_retained_earnings,quarterly_ebitda,quarterly_shares,quarterly_price,quarterly_market_cap,quarterly_eps,quarterly_pe_trailing,quarterly_forward_pe_snapshot,quarterly_forward_eps_snapshot,quarterly_pb,quarterly_ps,quarterly_ev,quarterly_ev_ebitda,quarterly_fcf,quarterly_fcf_yield,quarterly_revenue_growth_qoq,quarterly_earnings_growth_qoq,quarterly_ocf_growth_qoq,quarterly_fcf_growth_qoq,quarterly_roe,quarterly_roa,quarterly_gross_margin,quarterly_operating_margin,quarterly_debt_to_equity,quarterly_interest_coverage,quarterly_current_ratio,quarterly_quick_ratio,quarterly_X1,quarterly_X2,quarterly_X3,quarterly_X4,quarterly_X5,quarterly_altman_z,annual_net_income,annual_revenue,annual_gross_profit,annual_operating_income,annual_ebit,annual_interest_exp,annual_ocf,annual_capex,annual_shareholder_equity,annual_total_assets,annual_total_liabilities,annual_current_assets,annual_current_liab,annual_inventory,annual_total_debt,annual_cash,annual_retained_earnings,annual_shares,annual_price,annual_market_cap,annual_eps,annual_pe_trailing,annual_forward_pe_snapshot,annual_forward_eps_snapshot,annual_pb,annual_ps,annual_ev,annual_ebitda,annual_ev_ebitda,annual_fcf,annual_fcf_yield,annual_revenue_growth_yoy,annual_earnings_growth_yoy,annual_ocf_growth_yoy,annual_fcf_growth_yoy,annual_roe,annual_roa,annual_gross_margin,annual_operating_margin,annual_debt_to_equity,annual_interest_coverage,annual_current_ratio,annual_quick_ratio,annual_X1,annual_X2,annual_X3,annual_X4,annual_X5,annual_altman_z
fiscal_date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2024-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.555954,8.31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.699500e+10,3.832850e+11,1.691480e+11,1.143010e+11,1.143010e+11,3.933000e+09,1.105430e+11,NaN,NaN,3.525830e+11,NaN,NaN,NaN,6.331000e+09,1.110880e+11,2.996500e+10,-2.140000e+08,NaN,NaN,NaN,NaN,NaN,33.555954,8.31,None,NaN,NaN,1.258200e+11,NaN,NaN,NaN,-0.028005,-0.028135,-0.095030,NaN,NaN,0.275098,0.441311,0.298214,NaN,29.062039,NaN,NaN,NaN,-0.000607,0.324182,NaN,1.087077,NaN
2024-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.555954,8.31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.699500e+10,3.832850e+11,1.691480e+11,1.143010e+11,1.143010e+11,3.933000e+09,1.105430e+11,NaN,NaN,3.525830e+11,NaN,NaN,NaN,6.331000e+09,1.110880e+11,2.996500e+10,-2.140000e+08,NaN,NaN,NaN,NaN,NaN,33.555954,8.31,None,NaN,NaN,1.258200e+11,NaN,NaN,NaN,-0.028005,-0.028135,-0.095030,NaN,NaN,0.275098,0.441311,0.298214,NaN,29.062039,NaN,NaN,NaN,-0.000607,0.324182,NaN,1.087077,NaN
2024-09-30,1.473600e+10,9.493000e+10,4.387900e+10,2.959100e+10,2.959100e+10,NaN,2.681100e+10,NaN,5.695000e+10,3.649800e+11,NaN,1.529870e+11,1.763920e+11,7.286000e+09,1.066290e+11,2.994300e+10,-1.915400e+10,3.250200e+10,NaN,NaN,NaN,NaN,NaN,33.555954,8.31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.258753,0.040375,0.462225,0.311714,1.872327,NaN,0.867313,0.826007,-0.064127,-0.052480,0.081076,NaN,0.260096,NaN,9.373600e+10,3.910350e+11,1.806830e+11,1.232160e+11,1.232160e+11,NaN,1.182540e+11,NaN,NaN,3.649800e+11,NaN,NaN,NaN,7.286000e+09,1.066290e+11,2.994300e+10,-1.915400e+10,NaN,NaN,NaN,NaN,NaN,33.555954,8.31,None,NaN,NaN,1.346610e+11,NaN,NaN,NaN,0.020220,-0.033600,0.069756,NaN,NaN,0.256825,0.462063,0.315102,NaN,NaN,NaN,NaN,NaN,-0.052480,0.337597,NaN,1.071387,NaN
2024-12-31,3.633000e+10,1.243000e+11,5.827500e+10,4.283200e+10,4.283200e+10,NaN,2.993500e+10,NaN,6.675800e+10,3.440850e+11,NaN,1.332400e+11,1.443650e+11,6.911000e+09,9.679900e+10,3.029900e+10,-1.122100e+10,4.591200e+10,NaN,NaN,NaN,NaN,NaN,33.555954,8.31,NaN,NaN,NaN,NaN,NaN,NaN,0.309386,1.465391,0.116519,NaN,0.544204,0.105584,0.468825,0.344586,1.449999,NaN,0.922938,0.875067,-0.032332,-0.032611,0.124481,NaN,0.361248,NaN,9.373600e+10,3.910350e+11,1.806830e+11,1.232160e+11,1.232160e+11,NaN,1.182540e+11,NaN,NaN,3.649800e+11,NaN,NaN,NaN,7.286000e+09,1.066290e+11,2.994300e+10,-1.915400e+10,NaN,NaN,NaN,NaN,NaN,33.555954,8.31,None,NaN,NaN,1.346610e+11,NaN,NaN,NaN,0.020220,-0.033600,0.069756,NaN,NaN,0.256825,0.462063,0.315102,NaN,NaN,NaN,NaN,NaN,-0.052480,0.337597,NaN,1.071387,NaN
2025-03-31,2.478000e+10,9.535900e+10,4.486700e+10,2.958900e+10,2.958900e+10,NaN,2.395200e+10,NaN,6.679600e+10,3.312330e+11,NaN,1.186740e+11,1.445710e+11,6.269000e+09,9.818600e+10,2.816200e+10,-1.555200e+10,3.225000e+10,NaN,NaN,NaN,NaN,NaN,33.555954,8.31,NaN,NaN,NaN,NaN,NaN,NaN,-0.232832,-0.317919,-0.199866,NaN,0.370980,0.074811,0.470506,0.310291,1.469938,NaN,0.820870,0.777507,-0.078184,-0.046952,0.089330,NaN,0.287891,NaN,9.373600e+10,3.910350e+11,1.806830e+11,1.232160e+11,1.232160e+11,NaN,1.182540e+11,NaN,NaN,3.649800e+11,NaN,NaN,NaN,7.286000e+09,1.066290e+11,2.994300e+10,-1.915400e+10,NaN,NaN,NaN,NaN,NaN,33.555954,8.31,None,NaN,NaN,1.346610e+11,NaN,NaN,NaN,0.020220,-0.033600,0.069756,NaN,NaN,0.256825,0.462063,0.315102,NaN,NaN,NaN,NaN,NaN,-0.052480,0.337597,NaN,1.071387,NaN

In [19]:
aapl_financials.tail()

,quarterly_net_income,quarterly_revenue,quarterly_gross_profit,quarterly_operating_income,quarterly_ebit,quarterly_interest_exp,quarterly_ocf,quarterly_capex,quarterly_shareholder_equity,quarterly_total_assets,quarterly_total_liabilities,quarterly_current_assets,quarterly_current_liab,quarterly_inventory,quarterly_total_debt,quarterly_cash,quarterly_retained_earnings,quarterly_ebitda,quarterly_shares,quarterly_price,quarterly_market_cap,quarterly_eps,quarterly_pe_trailing,quarterly_forward_pe_snapshot,quarterly_forward_eps_snapshot,quarterly_pb,quarterly_ps,quarterly_ev,quarterly_ev_ebitda,quarterly_fcf,quarterly_fcf_yield,quarterly_revenue_growth_qoq,quarterly_earnings_growth_qoq,quarterly_ocf_growth_qoq,quarterly_fcf_growth_qoq,quarterly_roe,quarterly_roa,quarterly_gross_margin,quarterly_operating_margin,quarterly_debt_to_equity,quarterly_interest_coverage,quarterly_current_ratio,quarterly_quick_ratio,quarterly_X1,quarterly_X2,quarterly_X3,quarterly_X4,quarterly_X5,quarterly_altman_z,annual_net_income,annual_revenue,annual_gross_profit,annual_operating_income,annual_ebit,annual_interest_exp,annual_ocf,annual_capex,annual_shareholder_equity,annual_total_assets,annual_total_liabilities,annual_current_assets,annual_current_liab,annual_inventory,annual_total_debt,annual_cash,annual_retained_earnings,annual_shares,annual_price,annual_market_cap,annual_eps,annual_pe_trailing,annual_forward_pe_snapshot,annual_forward_eps_snapshot,annual_pb,annual_ps,annual_ev,annual_ebitda,annual_ev_ebitda,annual_fcf,annual_fcf_yield,annual_revenue_growth_yoy,annual_earnings_growth_yoy,annual_ocf_growth_yoy,annual_fcf_growth_yoy,annual_roe,annual_roa,annual_gross_margin,annual_operating_margin,annual_debt_to_equity,annual_interest_coverage,annual_current_ratio,annual_quick_ratio,annual_X1,annual_X2,annual_X3,annual_X4,annual_X5,annual_altman_z
fiscal_date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2024-09-30,1.473600e+10,9.493000e+10,4.387900e+10,2.959100e+10,2.959100e+10,NaN,2.681100e+10,NaN,5.695000e+10,3.649800e+11,NaN,1.529870e+11,1.763920e+11,7.286000e+09,1.066290e+11,2.994300e+10,-1.915400e+10,3.250200e+10,NaN,NaN,NaN,NaN,NaN,33.555954,8.31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.258753,0.040375,0.462225,0.311714,1.872327,NaN,0.867313,0.826007,-0.064127,-0.052480,0.081076,NaN,0.260096,NaN,9.373600e+10,3.910350e+11,1.806830e+11,1.232160e+11,1.232160e+11,NaN,1.182540e+11,NaN,NaN,3.649800e+11,NaN,NaN,NaN,7.286000e+09,1.066290e+11,2.994300e+10,-1.915400e+10,NaN,NaN,NaN,NaN,NaN,33.555954,8.31,None,NaN,NaN,1.346610e+11,NaN,NaN,NaN,0.020220,-0.033600,0.069756,NaN,NaN,0.256825,0.462063,0.315102,NaN,NaN,NaN,NaN,NaN,-0.052480,0.337597,NaN,1.071387,NaN
2024-12-31,3.633000e+10,1.243000e+11,5.827500e+10,4.283200e+10,4.283200e+10,NaN,2.993500e+10,NaN,6.675800e+10,3.440850e+11,NaN,1.332400e+11,1.443650e+11,6.911000e+09,9.679900e+10,3.029900e+10,-1.122100e+10,4.591200e+10,NaN,NaN,NaN,NaN,NaN,33.555954,8.31,NaN,NaN,NaN,NaN,NaN,NaN,0.309386,1.465391,0.116519,NaN,0.544204,0.105584,0.468825,0.344586,1.449999,NaN,0.922938,0.875067,-0.032332,-0.032611,0.124481,NaN,0.361248,NaN,9.373600e+10,3.910350e+11,1.806830e+11,1.232160e+11,1.232160e+11,NaN,1.182540e+11,NaN,NaN,3.649800e+11,NaN,NaN,NaN,7.286000e+09,1.066290e+11,2.994300e+10,-1.915400e+10,NaN,NaN,NaN,NaN,NaN,33.555954,8.31,None,NaN,NaN,1.346610e+11,NaN,NaN,NaN,0.020220,-0.033600,0.069756,NaN,NaN,0.256825,0.462063,0.315102,NaN,NaN,NaN,NaN,NaN,-0.052480,0.337597,NaN,1.071387,NaN
2025-03-31,2.478000e+10,9.535900e+10,4.486700e+10,2.958900e+10,2.958900e+10,NaN,2.395200e+10,NaN,6.679600e+10,3.312330e+11,NaN,1.186740e+11,1.445710e+11,6.269000e+09,9.818600e+10,2.816200e+10,-1.555200e+10,3.225000e+10,NaN,NaN,NaN,NaN,NaN,33.555954,8.31,NaN,NaN,NaN,NaN,NaN,NaN,-0.232832,-0.317919,-0.199866,NaN,0.370980,0.074811,0.470506,0.310291,1.469938,NaN,0.820870,0.777507,-0.078184,-0.046952,0.089330,NaN,0.287891,NaN,9.373600e+10,3.910350e+11,1.806830e+11,1.232160e+11,1.232160e+11,NaN,1.182540e+11,NaN,NaN,3.649800e+11,NaN,NaN,NaN,7.286000e+09,1.066290e+11,2.994300e+10,-1.915400e+10,NaN,NaN,NaN,NaN,NaN,33.555954,8.31,None,NaN,NaN,1.346610e+11,NaN,NaN,NaN,0.020220,-0.033600,0.069756,NaN,NaN,0.256825,0.462063,0.315102,NaN,NaN,NaN,NaN,NaN,-0.052480,0.337597,NaN,1.071387,NaN
2025-06-30,2.343400e+10,9.403600e+10,4.371800e+10,2.820200e+10,2.820200e+10,NaN,2.786700e+10,NaN,6.583000e+10,3.314950e+11,NaN,1.224910e+11,1.411200e+11,5.925000e+09,1.016980e+11,3.626900e+10,-1.760700e+10,3.103200e+10,NaN,NaN,NaN,NaN,NaN,33.555954,8.31,NaN,NaN,NaN,NaN,NaN,NaN,-0.013874,-0.054318,0.163452,NaN,0.355978,0.070692,0.464907,0.299906,1.544858,NaN,0.867992,0.826006,-0.056197,-0.053114,0.085075,NaN,0.283672,NaN,9.373600e+10,3.910350e+11,1.806830e+11,1.232160e+11,1.232160e+11,NaN,1.182540e+11,NaN,NaN,3.649800e+11,NaN,NaN,NaN,7.286000e+09,1.066290e+11,2.994300e+10,-1.915400e+10,NaN,NaN,NaN,NaN,NaN,33.555954,8.31,None,NaN,NaN,1.346610e+11,NaN,NaN,NaN,0.020220,-0.033600,0.069756,NaN,NaN,0.256825,0.462063,0.315102,NaN,NaN,NaN,NaN,NaN,-0.052480,0.337597,NaN,1.071387,NaN
2025-09-30,2.746600e+10,1.024660e+11,4.834100e+10,3.242700e+10,3.242700e+10,NaN,2.972800e+10,NaN,7.373300e+10,3.592410e+11,NaN,1.479570e+11,1.656310e+11,5.718000e+09,9.865700e+10,3.593400e+10,-1.426400e+10,3.555400e+10,NaN,NaN,NaN,NaN,NaN,33.555954,8.31,NaN,NaN,NaN,NaN,NaN,NaN,0.089647,0.172058,0.066781,NaN,0.372506,0.076456,0.471776,0.316466,1.338030,NaN,0.893293,0.858770,-0.049198,-0.039706,0.090265,NaN,0.285229,NaN,1.120100e+11,4.161610e+11,1.952010e+11,1.330500e+11,1.330500e+11,NaN,1.114820e+11,NaN,NaN,3.592410e+11,NaN,NaN,NaN,5.718000e+09,9.865700e+10,3.593400e+10,-1.426400e+10,NaN,NaN,NaN,NaN,NaN,33.555954,8.31,None,NaN,NaN,1.447480e+11,NaN,NaN,NaN,0.064255,0.194952,-0.057267,NaN,NaN,0.311796,0.469052,0.319708,NaN,NaN,NaN,NaN,NaN,-0.039706,0.370364,NaN,1.158445,NaN

In [20]:
aapl_financials.shape

(7, 98)

#### csv (row-wise)

In [21]:
# Read the timestamped CSV file using the environment variable path
aapl_csv_path = FUNDAMENTAL_PATH / "AAPL" / "AAPL_combined_factors_20251129_203256.csv"
aapl_financials_csv = pd.read_csv(aapl_csv_path)
# print(f"Loaded from: {aapl_csv_path}")
aapl_financials_csv.head()

,fiscal_date,quarterly_net_income,quarterly_revenue,quarterly_gross_profit,quarterly_operating_income,quarterly_ebit,quarterly_interest_exp,quarterly_ocf,quarterly_capex,quarterly_shareholder_equity,quarterly_total_assets,quarterly_total_liabilities,quarterly_current_assets,quarterly_current_liab,quarterly_inventory,quarterly_total_debt,quarterly_cash,quarterly_retained_earnings,quarterly_ebitda,quarterly_shares,quarterly_price,quarterly_market_cap,quarterly_eps,quarterly_pe_trailing,quarterly_forward_pe_snapshot,quarterly_forward_eps_snapshot,quarterly_pb,quarterly_ps,quarterly_ev,quarterly_ev_ebitda,quarterly_fcf,quarterly_fcf_yield,quarterly_revenue_growth_qoq,quarterly_earnings_growth_qoq,quarterly_ocf_growth_qoq,quarterly_fcf_growth_qoq,quarterly_roe,quarterly_roa,quarterly_gross_margin,quarterly_operating_margin,quarterly_debt_to_equity,quarterly_interest_coverage,quarterly_current_ratio,quarterly_quick_ratio,quarterly_X1,quarterly_X2,quarterly_X3,quarterly_X4,quarterly_X5,quarterly_altman_z,annual_net_income,annual_revenue,annual_gross_profit,annual_operating_income,annual_ebit,annual_interest_exp,annual_ocf,annual_capex,annual_shareholder_equity,annual_total_assets,annual_total_liabilities,annual_current_assets,annual_current_liab,annual_inventory,annual_total_debt,annual_cash,annual_retained_earnings,annual_shares,annual_price,annual_market_cap,annual_eps,annual_pe_trailing,annual_forward_pe_snapshot,annual_forward_eps_snapshot,annual_pb,annual_ps,annual_ev,annual_ebitda,annual_ev_ebitda,annual_fcf,annual_fcf_yield,annual_revenue_growth_yoy,annual_earnings_growth_yoy,annual_ocf_growth_yoy,annual_fcf_growth_yoy,annual_roe,annual_roa,annual_gross_margin,annual_operating_margin,annual_debt_to_equity,annual_interest_coverage,annual_current_ratio,annual_quick_ratio,annual_X1,annual_X2,annual_X3,annual_X4,annual_X5,annual_altman_z
0,2024-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.555954,8.31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.699500e+10,3.832850e+11,1.691480e+11,1.143010e+11,1.143010e+11,3.933000e+09,1.105430e+11,NaN,NaN,3.525830e+11,NaN,NaN,NaN,6.331000e+09,1.110880e+11,2.996500e+10,-2.140000e+08,NaN,NaN,NaN,NaN,NaN,33.555954,8.31,NaN,NaN,NaN,1.258200e+11,NaN,NaN,NaN,-0.028005,-0.028135,-0.095030,NaN,NaN,0.275098,0.441311,0.298214,NaN,29.062039,NaN,NaN,NaN,-0.000607,0.324182,NaN,1.087077,NaN
1,2024-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.555954,8.31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.699500e+10,3.832850e+11,1.691480e+11,1.143010e+11,1.143010e+11,3.933000e+09,1.105430e+11,NaN,NaN,3.525830e+11,NaN,NaN,NaN,6.331000e+09,1.110880e+11,2.996500e+10,-2.140000e+08,NaN,NaN,NaN,NaN,NaN,33.555954,8.31,NaN,NaN,NaN,1.258200e+11,NaN,NaN,NaN,-0.028005,-0.028135,-0.095030,NaN,NaN,0.275098,0.441311,0.298214,NaN,29.062039,NaN,NaN,NaN,-0.000607,0.324182,NaN,1.087077,NaN
2,2024-09-30,1.473600e+10,9.493000e+10,4.387900e+10,2.959100e+10,2.959100e+10,NaN,2.681100e+10,NaN,5.695000e+10,3.649800e+11,NaN,1.529870e+11,1.763920e+11,7.286000e+09,1.066290e+11,2.994300e+10,-1.915400e+10,3.250200e+10,NaN,NaN,NaN,NaN,NaN,33.555954,8.31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.258753,0.040375,0.462225,0.311714,1.872327,NaN,0.867313,0.826007,-0.064127,-0.052480,0.081076,NaN,0.260096,NaN,9.373600e+10,3.910350e+11,1.806830e+11,1.232160e+11,1.232160e+11,NaN,1.182540e+11,NaN,NaN,3.649800e+11,NaN,NaN,NaN,7.286000e+09,1.066290e+11,2.994300e+10,-1.915400e+10,NaN,NaN,NaN,NaN,NaN,33.555954,8.31,NaN,NaN,NaN,1.346610e+11,NaN,NaN,NaN,0.020220,-0.033600,0.069756,NaN,NaN,0.256825,0.462063,0.315102,NaN,NaN,NaN,NaN,NaN,-0.052480,0.337597,NaN,1.071387,NaN
3,2024-12-31,3.633000e+10,1.243000e+11,5.827500e+10,4.283200e+10,4.283200e+10,NaN,2.993500e+10,NaN,6.675800e+10,3.440850e+11,NaN,1.332400e+11,1.443650e+11,6.911000e+09,9.679900e+10,3.029900e+10,-1.122100e+10,4.591200e+10,NaN,NaN,NaN,NaN,NaN,33.555954,8.31,NaN,NaN,NaN,NaN,NaN,NaN,0.309386,1.465391,0.116519,NaN,0.544204,0.105584,0.468825,0.344586,1.449999,NaN,0.922938,0.875067,-0.032332,-0.032611,0.124481,NaN,0.361248,NaN,9.373600e+10,3.910350e+11,1.806830e+11,1.232160e+11,1.232160e+11,NaN,1.182540e+11,NaN,NaN,3.649800e+11,NaN,NaN,NaN,7.286000e+09,1.066290e+11,2.994300e+10,-1.915400e+10,NaN,NaN,NaN,NaN,NaN,33.555954,8.31,NaN,NaN,NaN,1.346610e+11,NaN,NaN,NaN,0.020220,-0.033600,0.069756,NaN,NaN,0.256825,0.462063,0.315102,NaN,NaN,NaN,NaN,NaN,-0.052480,0.337597,NaN,1.071387,NaN
4,2025-03-31,2.478000e+10,9.535900e+10,4.486700e+10,2.958900e+10,2.958900e+10,NaN,2.395200e+10,NaN,6.679600e+10,3.312330e+11,NaN,1.186740e+11,1.445710e+11,6.269000e+09,9.818600e+10,2.816200e+10,-1.555200e+10,3.225000e+10,NaN,NaN,NaN,NaN,NaN,33.555954,8.31,NaN,NaN,NaN,NaN,NaN,NaN,-0.232832,-0.317919,-0.199866,NaN,0.370980,0.074811,0.470506,0.310291,1.469938,NaN,0.820870,0.777507,-0.078184,-0.046952,0.089330,NaN,0.287891,NaN,9.373600e+10,3.910350e+11,1.806830e+11,1.232160e+11,1.232160e+11,NaN,1.182540e+11,NaN,NaN,3.649800e+11,NaN,NaN,NaN,7.286000e+09,1.066290e+11,2.994300e+10,-1.915400e+10,NaN,NaN,NaN,NaN,NaN,33.555954,8.31,NaN,NaN,NaN,1.346610e+11,NaN,NaN,NaN,0.020220,-0.033600,0.069756,NaN,NaN,0.256825,0.462063,0.315102,NaN,NaN,NaN,NaN,NaN,-0.052480,0.337597,NaN,1.071387,NaN

In [22]:
aapl_financials_csv.shape

(7, 99)

In [23]:
# Example: How to construct paths for any ticker
ticker = "AAPL"

# Latest parquet files
combined_factors_path = FUNDAMENTAL_PATH / ticker / f"{ticker}_combined_factors_latest.parquet"
eps_surprises_path = FUNDAMENTAL_PATH / ticker / f"{ticker}_eps_surprises_latest.parquet"
metadata_path = FUNDAMENTAL_PATH / ticker / f"{ticker}_metadata_latest.csv"

# Summary file
summary_path = FUNDAMENTAL_PATH / "data_summary.csv"

# print(f"Combined factors: {combined_factors_path}")
# print(f"EPS surprises: {eps_surprises_path}")
# print(f"Metadata: {metadata_path}")
# print(f"Summary: {summary_path}")

### AAPL eps surprise (Parquet)

In [24]:
# Read the latest AAPL parquet file using the environment variable path
aapl_eps_path = FUNDAMENTAL_PATH / "AAPL" / "AAPL_eps_surprises_latest.parquet"
aapl_eps = pd.read_parquet(aapl_eps_path)
# print(f"Loaded from: {aapl_eps_path}")
aapl_eps.head()

,eps_estimate,eps_actual,eps_surprise,eps_surprise_pct
Earnings Date,,,,
2026-01-29 16:00:00-05:00,2.66,NaN,NaN,NaN
2025-10-30 16:00:00-04:00,1.77,1.85,0.08,0.045198
2025-07-31 16:00:00-04:00,1.43,1.57,0.14,0.097902
2025-05-01 16:00:00-04:00,1.63,1.65,0.02,0.012270
2025-01-30 16:00:00-05:00,2.35,2.40,0.05,0.021277

In [25]:
aapl_eps.shape

(25, 4)

In [26]:
aapl_eps.tail()

,eps_estimate,eps_actual,eps_surprise,eps_surprise_pct
Earnings Date,,,,
2021-01-27 16:00:00-05:00,1.42,1.68,0.26,0.183099
2020-10-29 16:00:00-04:00,0.70,0.73,0.03,0.042857
2020-07-30 16:00:00-04:00,0.52,0.65,0.13,0.250000
2020-04-30 17:00:00-04:00,0.56,0.64,0.08,0.142857
2020-01-28 16:00:00-05:00,1.13,1.25,0.12,0.106195

there's eps surprise quarterly historical data since 2020 (eps surprise per each quarter earnings), but not the same for the other financials like balance sheet, income, cashflow

EPS surprise is available quarterly because eps does not come from the balance sheet / cashflow statements, but from the earnings calendar endpoints on Yahoo, storing earnings estimates & reported eps per quarter.

in short, earnings dates can be collected historically further back than the balance sheet or cashflow statements. EPS can be  derived directly from these earnings dates.